name: Build and Release Game

on:
  push:
    tags:
      - 'v*'

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Export Game
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          use_preset_export_path: true

      - name: Zip Windows Build
        run: |
          cd builds/windows
          zip -r ../../Windows_Desktop.zip .
          cd ../..

      - name: Zip Linux Build
        run: |
          cd builds/linux
          zip -r ../../Linux.zip .
          cd ../..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Windows_Desktop.zip
            Linux.zip
